### ISSUE TITLE
AttributeError: module 'stltools.utils' has no attribute 'Msg'

### ISSUE THREAD

**Issue by kjcole** [rsmith-nl/stltools#6]
Using commit aed6dd02127b22fc5c5b71fe4bce8aae130eda17

```
$  stl2pov assembly_v4_rev3.stl 
Traceback (most recent call last):
  File "/usr/local/bin/stl2pov", line 4, in <module>
    __import__('pkg_resources').run_script('stltools==4.0.0', 'stl2pov')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/stltools-4.0.0-py3.5.egg/EGG-INFO/scripts/stl2pov", line 129, in <module>
  File "/usr/local/lib/python3.5/dist-packages/stltools-4.0.0-py3.5.egg/EGG-INFO/scripts/stl2pov", line 84, in main
AttributeError: module 'stltools.utils' has no attribute 'Msg'
```

**Comment by rsmith-nl** [comment]
Since the `Msg` function doesn't exist anymore in the 4.0.0 code, I suspect this is an issue of remaining code from an older version. Try removing all traces of stltools and then re-installing.

**Comment by kjcole** [comment]
Oops.
